version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/wallet"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "Miracle656"

  - package-ecosystem: "npm"
    directory: "/frontend/website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "Miracle656"

  - package-ecosystem: "npm"
    directory: "/frontend/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "Miracle656"

  - package-ecosystem: "npm"
    directory: "/sdk"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "Miracle656"

  - package-ecosystem: "npm"
    directory: "/packages/agent"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "Miracle656"

  - package-ecosystem: "cargo"
    directory: "/contracts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "Miracle656"